language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: c8Ayag/g86hsQErtL1/RUSPEDzOsFh8jaVxrcjnxh08cTM1gxpjlkQ/fZQveF7GiLBRqTEmG00kxPYp/j7R20uqPjcMC2A/mGCp3BG3lIRahFxqRK18pXXXc04UESMEgUrBQMYsBQ7boDchq5hizi5l6f6+/t5QVrwuXndvRwsc=
  - secure: NR7c9kLebol4YLORtgEMoxKEPmtcywaHxNUyHl+0I7WKIopSxMAsM4qeghPtvEVrmoNZmuv6xy4HqWrFfRgHaMEIdIlOvTK30AbxotyJFgmY1zkWkUZ6QnXfDCgFIZ5FSxAcCv5i3/kHSj2eqFMCC9PclCKKX5pcgQTOby2Wjmo=
addons:
  sauce_connect: true